import { isAdmin } from '@/lib/auth';
import { prisma } from '@/lib/db/prisma';
import { formatKorea } from '@/lib/time/korea';
import { AnalysisSchema } from '@/lib/ai/schemas';
import AdminControls from './ui';
export const dynamic = 'force-dynamic';
export const metadata = { title: '관리자', robots: { index: false, follow: false } };
export default async function AdminPage() {
    if (!await isAdmin())
        return <main id="main" className="login"><p className="eyebrow">NOAH / CONTROL ROOM</p><h1>관리자 로그인</h1><p>운영자 전용 페이지입니다.</p><form action="/api/admin/session" method="post"><label htmlFor="secret">관리자 비밀키</label><input id="secret" name="secret" type="password" required autoComplete="current-password" minLength={24}/><button type="submit">로그인 →</button></form><p className="muted">관리자 키가 설정되지 않은 환경에서는 로그인할 수 없습니다.</p></main>;
    const [logs, events, arks, breaking] = await Promise.all([prisma.pipelineLog.findMany({ orderBy: { startedAt: 'desc' }, take: 15 }), prisma.event.findMany({ orderBy: { finalScore: 'desc' }, take: 30 }), prisma.dailyArk.findMany({ orderBy: { arkDate: 'desc' }, take: 7 }), prisma.breakingCandidate.findMany({ orderBy: { createdAt: 'desc' }, take: 10, include: { event: { select: { representativeTitle: true } } } })]);
    const last = logs[0];
    return <main id="main" className="admin"><div className="admin-title"><div><p className="eyebrow">NOAH / CONTROL ROOM</p><h1>운영 현황</h1></div><form action="/api/admin/session" method="post"><input name="logout" value="1" type="hidden"/><button className="secondary">로그아웃</button></form></div><AdminControls /><section><h2>Last Pipeline</h2>{last ? <><p>{formatKorea(last.startedAt)} KST · {last.type} · <strong>{last.status}</strong></p><div className="metrics">{[['수집', last.articlesFetched], ['저장', last.articlesInserted], ['중복', last.duplicatesRemoved], ['새 Event', last.eventsCreated], ['Event 갱신', last.eventsUpdated], ['분석 성공', last.aiSuccess], ['분석 실패', last.aiFailed]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></> : <p>아직 실행 기록이 없습니다.</p>}</section><section><h2>Today’s Ark</h2>{arks.map(a => <p key={a.id}>{a.arkDate} · {a.eventCount}개 · {a.status}{a.isMock ? ' · MOCK' : ''}</p>)}</section><section><h2>개인 관련성 <small>비공개 · USER IMPLICATION</small></h2>{events.map(e => { const a = AnalysisSchema.safeParse(e.analysis); return <details key={e.id}><summary>{e.representativeTitle} · {e.grade} · {e.analysisStatus}</summary><p>중요도 {e.importanceScore} / 관련성 {e.relevanceScore} / 최종 {e.finalScore} / 긴급 {e.breakingScore}</p><p>{a.success ? a.data.userImplication : e.analysisError ?? '분석 대기 중'}</p></details>; })}</section><section><h2>긴급 변화 후보</h2><p className="muted">의미 있는 변화 단위로 기록합니다. Push 알림은 발송하지 않습니다.</p>{breaking.length ? breaking.map(b => <p key={b.id}>{b.event.representativeTitle} · {b.score}</p>) : <p>기준을 충족한 긴급 후보가 없습니다.</p>}</section><section><h2>Pipeline Logs & Errors</h2><div className="table-wrap"><table><thead><tr><th>시작 KST</th><th>종류</th><th>상태</th><th>오류</th></tr></thead><tbody>{logs.map(log => <tr key={log.id}><td>{formatKorea(log.startedAt)}</td><td>{log.type}</td><td>{log.status}</td><td>{log.errorMessage ?? '—'}</td></tr>)}</tbody></table></div></section></main>;
}
