import Link from 'next/link';
import EventCard from './EventCard';
import { getArk, getArchives, snapshot } from '@/lib/data';
import { formatKorea } from '@/lib/time/korea';
import InvestorIntro from './InvestorIntro';
export default async function ArkReport({ ark }: {
    ark: NonNullable<Awaited<ReturnType<typeof getArk>>>;
}) {
    const archives = await getArchives();
    return <main id="main">{ark.isMock && <InvestorIntro count={ark.eventCount}/>}<div className="report-top"><span>DAILY INTELLIGENCE REPORT</span><span>{ark.arkDate.replaceAll('-', '.')} <i> / </i> 07:00 KST</span></div><section className="ark-heading"><div><p className="eyebrow">ONLY WHAT MATTERS.</p><h1>Today’s <em>Ark.</em></h1><p className="intro">정보의 홍수에서,<br />오늘 반드시 알아야 할 <strong>{ark.eventCount}개의 변화.</strong></p></div><div className="edition"><span>SELECTED SIGNALS</span><strong>{String(ark.eventCount).padStart(2, '0')}</strong><span>최대 10개, 중요한 변화만</span></div></section>{ark.isMock && <div className="demo-banner"><strong>DEMO EDITION</strong><span>가상 기사로 실행한 보고서입니다. 실제 뉴스·공고가 아니며, 원문 주소도 예시입니다.</span></div>}<div className="report-layout"><div className="events">{ark.items.length ? ark.items.map(item => <EventCard key={item.id} event={snapshot(item.snapshot)} rank={item.rank}/>) : <div className="empty"><h2>오늘은 선별 기준을 통과한 변화가 없습니다.</h2><p>개수를 채우기 위해 중요하지 않은 정보를 추가하지 않습니다.</p></div>}</div><aside><div className="sidebar-block"><p className="eyebrow">IN THIS ARK</p>{Object.entries(ark.items.reduce<Record<string, number>>((acc, item) => { const c = snapshot(item.snapshot).primaryCategory; acc[c] = (acc[c] ?? 0) + 1; return acc; }, {})).map(([category, count]) => <div className="category-row" key={category}><span>{({ POLICY: '정책·행정', REAL_ESTATE: '부동산·주거', FINANCE: '금융', AI_TECH: 'AI·기술', NEURO_EDU: '뇌과학·교육', REGIONAL: '지역', OTHER: '기타' })[category]}</span><strong>{count}</strong></div>)}</div><div className="sidebar-block method"><p className="eyebrow">THE NOAH FILTER</p><h3>많은 기사.<br />적은 변화.<br />명확한 맥락.</h3><p>같은 사건의 보도를 하나로 묶고, 중요성과 관련성을 평가합니다. B 등급 이상만 Ark에 담습니다.</p><span>수집 범위 · KST</span><p>{formatKorea(ark.periodStart)}<br />— {formatKorea(ark.periodEnd)} 미만</p></div><div className="sidebar-block" id="archive"><p className="eyebrow">PREVIOUS ARKS</p>{archives.map(a => <Link className="archive-row" key={a.arkDate} href={`/ark/${a.arkDate}`}><span>{a.arkDate}</span><span>{a.eventCount}개 →</span></Link>)}</div></aside></div></main>;
}
